### ISSUE TITLE
05-05-02 ResourceQuota error

### ISSUE THREAD

**Issue by VicNine** [stacksimplify/aws-eks-kubernetes-masterclass#40]
Position: 

> 05-Kubernetes-Important-Concepts-for-Application-Deployments/05-05-Kubernetes-Namespaces/05-05-02-Namespaces-LimitRange-default

Error: 
``` yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: dev3
```
Fix: `kind: LimitRange`
